// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqKLggv19RaFTgq7T38WqizrOSZsaUbQ',
    appId: '1:589814950349:web:8ea2d04b0e036f4e83bc84',
    messagingSenderId: '589814950349',
    projectId: 'chat-app-42724',
    authDomain: 'chat-app-42724.firebaseapp.com',
    storageBucket: 'chat-app-42724.appspot.com',
    measurementId: 'G-VE33FN69TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMefNFkvt-tpO-Fz9ZVqu-7xiM4W-mNk',
    appId: '1:589814950349:android:74e6bef871f1380983bc84',
    messagingSenderId: '589814950349',
    projectId: 'chat-app-42724',
    storageBucket: 'chat-app-42724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbMSqaEGwYvljBb7uqpcv4vBMuv6I7YOk',
    appId: '1:589814950349:ios:16c419db46af46cf83bc84',
    messagingSenderId: '589814950349',
    projectId: 'chat-app-42724',
    storageBucket: 'chat-app-42724.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbMSqaEGwYvljBb7uqpcv4vBMuv6I7YOk',
    appId: '1:589814950349:ios:4eee8c4195d0168783bc84',
    messagingSenderId: '589814950349',
    projectId: 'chat-app-42724',
    storageBucket: 'chat-app-42724.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
